### ISSUE TITLE
task 1: Tìm kiếm template (thiết kế) trang web sử dụng AdobeXd 

### ISSUE THREAD

**Issue by minhhiennn** [minhhiennn/ProjectFrontEnd#2]
phân chia công việc :
các bạn trong nhóm sẽ tìm hiểu về AdobeXd để vẽ UI cho trang web

**Comment by minhhiennn** [comment]
phân công việc vẽ AdobeXd cho trang web:
bạn Hiển: index,login,shop,contact-us
bạn Văn Anh: 404,blog-blog-details
bạn Phùng:product-detail,cart,checkout

**Comment by minhhiennn** [comment]
cập nhât: các bạn đã vẽ và nộp bài theo đúng hạn

**Comment by phungle2508** [comment]
> cập nhât: các bạn đã vẽ và nộp bài theo đúng hạn

hoan thanh

**Comment by damanh1905** [comment]
hoàn thành
